version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-dev
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
      - /workspace/vendor
      - /workspace/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"  # Vite dev server
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=progesio_ips
      - DB_USERNAME=progesio_root
      - DB_PASSWORD=admin@moflip.com
    depends_on:
      - mysql
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin@moflip.com
      MYSQL_DATABASE: progesio_ips
      MYSQL_USER: progesio_root
      MYSQL_PASSWORD: admin@moflip.com
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - laravel-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: progesio_root
      PMA_PASSWORD: admin@moflip.com
    depends_on:
      - mysql
    networks:
      - laravel-network

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge
